# -- accelerate/default_config.yaml --
# Config for a full bf16 fine-tune of an 8B model on one machine with one GPU.

compute_environment: LOCAL_MACHINE
distributed_type: DEEPSPEED
downcast_bf16: 'no'
gpu_ids: 'all'
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 1
use_cpu: false

# DeepSpeed config for hardware and offloading ONLY
deepspeed_config:
  deepspeed_multinode_launcher: standard
  zero_stage: 3
  
  offload_param:
    device: cpu
    pin_memory: true
  
  offload_optimizer:
    device: cpu
    pin_memory: true

  bf16:
    enabled: true
    optimizer_dtype: bf16

  activation_checkpointing:
    partition_activations: true
    cpu_checkpointing: true
    contiguous_memory_optimization: false
    synchronize_checkpoint_boundary: false